-- Create your project database
CREATE DATABASE FMCG_ANALYTICS;

-- Create three schemas like a real BI project
CREATE SCHEMA FMCG_ANALYTICS.RAW;
CREATE SCHEMA FMCG_ANALYTICS.STAGING;
CREATE SCHEMA FMCG_ANALYTICS.REPORTING;

-- Create a dedicated warehouse for this project
CREATE WAREHOUSE FMCG_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE FMCG_WH;
USE DATABASE FMCG_ANALYTICS;

SHOW DATABASES;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS LIMIT 10;