-- Copy sample data into your RAW schema
CREATE TABLE FMCG_ANALYTICS.RAW.ORDERS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

CREATE TABLE FMCG_ANALYTICS.RAW.LINEITEM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

CREATE TABLE FMCG_ANALYTICS.RAW.CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE TABLE FMCG_ANALYTICS.RAW.PART AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

-- Verify row counts
WITH source AS (
    SELECT 'ORDERS' as tbl, COUNT(*) as cnt 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
    UNION ALL
    SELECT 'LINEITEM', COUNT(*) 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
    UNION ALL
    SELECT 'CUSTOMER', COUNT(*) 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
    UNION ALL
    SELECT 'PART', COUNT(*) 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART
),
destination AS (
    SELECT 'ORDERS' as tbl, COUNT(*) as cnt 
    FROM FMCG_ANALYTICS.RAW.ORDERS
    UNION ALL
    SELECT 'LINEITEM', COUNT(*) 
    FROM FMCG_ANALYTICS.RAW.LINEITEM
    UNION ALL
    SELECT 'CUSTOMER', COUNT(*) 
    FROM FMCG_ANALYTICS.RAW.CUSTOMER
    UNION ALL
    SELECT 'PART', COUNT(*) 
    FROM FMCG_ANALYTICS.RAW.PART
)
SELECT 
    s.tbl                                    AS table_name,
    s.cnt                                    AS source_rows,
    d.cnt                                    AS raw_rows,
    CASE 
        WHEN s.cnt = d.cnt THEN 'MATCH - OK'
        ELSE 'MISMATCH - INVESTIGATE'
    END                                      AS validation_status
FROM source s
JOIN destination d ON s.tbl = d.tbl
ORDER BY s.tbl;